/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SidebarRouteImport } from './routes/_sidebar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as SidebarSettingsRouteImport } from './routes/_sidebar/settings'
import { Route as SidebarHomeRouteImport } from './routes/_sidebar/home'
import { Route as SidebarHistoryRouteImport } from './routes/_sidebar/history'
import { Route as SidebarCalendarRouteImport } from './routes/_sidebar/calendar'
import { Route as SidebarAddProductRouteImport } from './routes/_sidebar/add-product'

const SidebarRoute = SidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarSettingsRoute = SidebarSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarHomeRoute = SidebarHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarHistoryRoute = SidebarHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarCalendarRoute = SidebarCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarAddProductRoute = SidebarAddProductRouteImport.update({
  id: '/add-product',
  path: '/add-product',
  getParentRoute: () => SidebarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-product': typeof SidebarAddProductRoute
  '/calendar': typeof SidebarCalendarRoute
  '/history': typeof SidebarHistoryRoute
  '/home': typeof SidebarHomeRoute
  '/settings': typeof SidebarSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-product': typeof SidebarAddProductRoute
  '/calendar': typeof SidebarCalendarRoute
  '/history': typeof SidebarHistoryRoute
  '/home': typeof SidebarHomeRoute
  '/settings': typeof SidebarSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteWithChildren
  '/_sidebar/add-product': typeof SidebarAddProductRoute
  '/_sidebar/calendar': typeof SidebarCalendarRoute
  '/_sidebar/history': typeof SidebarHistoryRoute
  '/_sidebar/home': typeof SidebarHomeRoute
  '/_sidebar/settings': typeof SidebarSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-product'
    | '/calendar'
    | '/history'
    | '/home'
    | '/settings'
    | '/auth/login'
    | '/auth/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-product'
    | '/calendar'
    | '/history'
    | '/home'
    | '/settings'
    | '/auth/login'
    | '/auth/signup'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/add-product'
    | '/_sidebar/calendar'
    | '/_sidebar/history'
    | '/_sidebar/home'
    | '/_sidebar/settings'
    | '/auth/login'
    | '/auth/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRoute: typeof SidebarRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/settings': {
      id: '/_sidebar/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SidebarSettingsRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/home': {
      id: '/_sidebar/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof SidebarHomeRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/history': {
      id: '/_sidebar/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof SidebarHistoryRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/calendar': {
      id: '/_sidebar/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof SidebarCalendarRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/add-product': {
      id: '/_sidebar/add-product'
      path: '/add-product'
      fullPath: '/add-product'
      preLoaderRoute: typeof SidebarAddProductRouteImport
      parentRoute: typeof SidebarRoute
    }
  }
}

interface SidebarRouteChildren {
  SidebarAddProductRoute: typeof SidebarAddProductRoute
  SidebarCalendarRoute: typeof SidebarCalendarRoute
  SidebarHistoryRoute: typeof SidebarHistoryRoute
  SidebarHomeRoute: typeof SidebarHomeRoute
  SidebarSettingsRoute: typeof SidebarSettingsRoute
}

const SidebarRouteChildren: SidebarRouteChildren = {
  SidebarAddProductRoute: SidebarAddProductRoute,
  SidebarCalendarRoute: SidebarCalendarRoute,
  SidebarHistoryRoute: SidebarHistoryRoute,
  SidebarHomeRoute: SidebarHomeRoute,
  SidebarSettingsRoute: SidebarSettingsRoute,
}

const SidebarRouteWithChildren =
  SidebarRoute._addFileChildren(SidebarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRoute: SidebarRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
